<?php
// Include the database connection
include 'php/connection.php'; 
session_start();

if (isset($_POST['submit'])) {
    // Sanitize and retrieve form inputs
    $firstname = mysqli_real_escape_string($connection, $_POST['firstname']);
    $middlename = mysqli_real_escape_string($connection, $_POST['middlename']);
    $lastname = mysqli_real_escape_string($connection, $_POST['lastname']);
    $email = mysqli_real_escape_string($connection, $_POST['email']);
    $birthday = mysqli_real_escape_string($connection, $_POST['birthday']);
    $contact = mysqli_real_escape_string($connection, $_POST['contact']);
    $password = mysqli_real_escape_string($connection, $_POST['password']);
    $cpassword = mysqli_real_escape_string($connection, $_POST['cpassword']);
    $gender = mysqli_real_escape_string($connection, $_POST['Gender']);
    $gender = strtoupper(substr($gender, 0, 1)); // Convert to 'M' or 'F'
    $status = "Active"; // Default status

    // Handle image uploads
    $image = isset($_FILES['image']['name']) ? $_FILES['image']['name'] : '';
    $image_size = isset($_FILES['image']['size']) ? $_FILES['image']['size'] : 0;
    $image_tmp_name = isset($_FILES['image']['tmp_name']) ? $_FILES['image']['tmp_name'] : '';
    $image_folder = !empty($image) ? 'img/' . uniqid() . '-' . basename($image) : '';

    // Password validation
    if ($password !== $cpassword) {
        echo "<script>alert('Passwords do not match!');</script>";
    } else {
        // Check if the email already exists
        $check_email = mysqli_query($connection, "SELECT * FROM `patient` WHERE `Email` = '$email'");
        if (mysqli_num_rows($check_email) > 0) {
            echo "<script>alert('Email already exists!');</script>";
        } else {
            // Check if image size is too large
            if (!empty($image) && $image_size > 10000000) {
                echo "<script>alert('Image size is too large!');</script>";
            } else {
                // Move uploaded image to the target folder
                if (!empty($image)) {
                    move_uploaded_file($image_tmp_name, $image_folder);
                }

                // Calculate age from birthday
                $birthday_date = new DateTime($birthday);
                $current_date = new DateTime();
                $age = $current_date->diff($birthday_date)->y;

                // Insert user data into the `patient` table (PatientID is auto-generated by the trigger)
                $password_hash = password_hash($password, PASSWORD_BCRYPT); // Secure password hashing
                $query = "
                    INSERT INTO `patient` 
                    (`Firstname`, `Middlename`, `Lastname`, `Sex`, `Birthday`, `Age`, `ContactDetails`, `Email`, `password`, `img`, `status`) 
                    VALUES 
                    ('$firstname', '$middlename', '$lastname', '$gender', '$birthday', '$age', '$contact', '$email', '$password_hash', '$image_folder', '$status')
                ";

                if (mysqli_query($connection, $query)) {
                    echo "<script>
                            alert('Registration successful!');
                            window.location.href = 'login.php';
                          </script>";
                } else {
                    echo "<script>alert('Error: " . mysqli_error($connection) . "');</script>";
                }
            }
        }
    }
}
?>





<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="icons/patient/toothlogos.png">
    <link rel="stylesheet" href="css/register.css"> <!-- Link your CSS file -->
    <title>Register Page</title>
</head>
<body>
    <div class="header">
        <a href="index.php"><img src="icons/patient/seek4smilesLogo.png" alt=""></a>
    </div>

    <div class="container">
        <div class="background-overlay" style="background-image: url('icons/patient/background.png');"></div>

        <div class="form-container">
            <form action="" method="post" enctype="multipart/form-data">
                <div class="tabs">
                    <a href="login.php">SIGN IN</a>
                    <a href="#" class="active">SIGN UP</a>
                </div>

                <h3>Create Account</h3>
                <p class="subtitle">Book an appointment and access medical records, anytime, anywhere.</p>
                
                <div class="input-group">
                    <?php 
                        if (!empty($alert)) {
                            foreach ($alert as $err) {
                                echo "<h3 class=\"alert\">$err</h3>";
                            }
                        }
                    ?>
                    <form method="POST" enctype="multipart/form-data">
                        <input type="text" name="firstname" placeholder="Enter Firstname" class="box" required>
                        <input type="text" name="middlename" placeholder="Enter Middlename" class="box">
                        <input type="text" name="lastname" placeholder="Enter Lastname" class="box" required>
                        <input type="email" name="email" placeholder="Enter Email" class="box" required>
                        <input type="date" name="birthday" placeholder="Enter Birthday" class="box" required min="1950-01-01" max="<?php echo date('Y-m-d'); ?>">
                        <input type="text" name="contact" placeholder="Enter Contact Number" class="box" required maxlength="11" oninput="this.value = this.value.replace(/[^0-9]/g, '');">
                        <input type="password" name="password" placeholder="Enter Password" class="box" required>
                        <input type="password" name="cpassword" placeholder="Confirm Password" class="box" required>
                        <select name="Gender" class="box" required>
                            <option value="" disabled selected>Select Gender</option>
                            <option value="male">Male</option>
                            <option value="female">Female</option>
                        </select>
                        <input type="file" name="image" class="box" accept="image/*">
                        <button type="submit" name="submit" class="btn">Submit</button>
                    </form>
                </div>
                <div class="footer-links">
                    <a href="#">Privacy Policy</a>
                    <a href="#">Terms of Use</a>
                </div>
            </form>
        </div>   
    </div>
<script>
    // for limit of numbers
    document.querySelector('input[name="contact"]').addEventListener('input', function (e) {
      e.target.value = e.target.value.replace(/[^0-9]/g, '');
    });

    document.querySelector('form').addEventListener('submit', function(event) {
        let form = event.target;
        let valid = true;

        // Reset error styles
        form.querySelectorAll('.box').forEach(input => {
            input.style.borderColor = '';
        });

        // Validate inputs
        form.querySelectorAll('.box').forEach(input => {
            if (!input.checkValidity()) {
                valid = false;
                input.style.borderColor = 'red';
                input.value = ''; // Reset only the invalid input
            }
        });

        // Check if passwords match
        let password = form.querySelector('input[name="password"]');
        let cpassword = form.querySelector('input[name="cpassword"]');
        if (password.value !== cpassword.value) {
            valid = false;
            password.style.borderColor = 'red';
            cpassword.style.borderColor = 'red';
            password.value = '';
            cpassword.value = '';
        }

        if (!valid) {
            event.preventDefault();
        }
    });
</script>
</body>
</html>